version: '3.1'
services :
  store-db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    env_file: './.env'
  admin:
    image: adminer
    restart: always
    depends_on: 
      - store-db
    ports:
      - 8080:8080
  
  
    

  
